### PR TITLE
Upgrade Micronaut Kafka to 5.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by graemerocher**
Remove `managed-kafka` since this version is managed by the Micronaut Kafka BOM

### CODE REVIEW

**Comment by melix** [comment]
The catalog complains that you removed the `managed-kafka` version which is used independently of `micronaut-kafka`: that was for the kafka 2.12 version. I am unsure if we should remove as well.

**Comment by graemerocher** [comment]
it is defined here https://github.com/micronaut-projects/micronaut-kafka/blob/ec6be6cb7bf9f61b5d59bf35ead2fa3ec46c2276/gradle/libs.versions.toml#L7

**Comment by melix** [comment]
I don't understand what you're saying. This PR removes `managed-kafka`, but it's used as part of the catalog: https://ge.micronaut.io/s/fy65mk7ptjwaa/failure?focused-exception-line=0-3#1

**Comment by graemerocher** [comment]
Ok I see I removed this reference. Not sure where if anywhere it used frankly.

**Pull request merged**
